version: '3.7'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    # image: hiha-store-ts:v1
    volumes:
      - ./src:/app/src
    ports:
      - 3001:3000
    # restart: unless-stopped
